/*
 * This file is generated by jOOQ.
 */
package com.msj.securefile.shared.infrastructure.persistence.jooq.storage.tables.records;


import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.tables.FileEvent;

import java.time.Instant;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FileEventRecord extends UpdatableRecordImpl<FileEventRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>storage.file_event.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>storage.file_event.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>storage.file_event.file_id</code>.
     */
    public void setFileId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>storage.file_event.file_id</code>.
     */
    public Long getFileId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>storage.file_event.aggregate_type</code>.
     */
    public void setAggregateType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>storage.file_event.aggregate_type</code>.
     */
    public String getAggregateType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>storage.file_event.aggregate_id</code>.
     */
    public void setAggregateId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>storage.file_event.aggregate_id</code>.
     */
    public Long getAggregateId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>storage.file_event.version</code>.
     */
    public void setVersion(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>storage.file_event.version</code>.
     */
    public Long getVersion() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>storage.file_event.event_type</code>.
     */
    public void setEventType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>storage.file_event.event_type</code>.
     */
    public String getEventType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>storage.file_event.payload</code>.
     */
    public void setPayload(JSONB value) {
        set(6, value);
    }

    /**
     * Getter for <code>storage.file_event.payload</code>.
     */
    public JSONB getPayload() {
        return (JSONB) get(6);
    }

    /**
     * Setter for <code>storage.file_event.actor_type</code>.
     */
    public void setActorType(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>storage.file_event.actor_type</code>.
     */
    public String getActorType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>storage.file_event.actor_id</code>.
     */
    public void setActorId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>storage.file_event.actor_id</code>.
     */
    public String getActorId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>storage.file_event.occurred_at</code>.
     */
    public void setOccurredAt(Instant value) {
        set(9, value);
    }

    /**
     * Getter for <code>storage.file_event.occurred_at</code>.
     */
    public Instant getOccurredAt() {
        return (Instant) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileEventRecord
     */
    public FileEventRecord() {
        super(FileEvent.FILE_EVENT);
    }

    /**
     * Create a detached, initialised FileEventRecord
     */
    public FileEventRecord(Long id, Long fileId, String aggregateType, Long aggregateId, Long version, String eventType, JSONB payload, String actorType, String actorId, Instant occurredAt) {
        super(FileEvent.FILE_EVENT);

        setId(id);
        setFileId(fileId);
        setAggregateType(aggregateType);
        setAggregateId(aggregateId);
        setVersion(version);
        setEventType(eventType);
        setPayload(payload);
        setActorType(actorType);
        setActorId(actorId);
        setOccurredAt(occurredAt);
        resetTouchedOnNotNull();
    }
}
