/*
 * This file is generated by jOOQ.
 */
package com.msj.securefile.shared.infrastructure.persistence.jooq.storage.tables.records;


import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.tables.ScanJob;

import java.time.Instant;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScanJobRecord extends UpdatableRecordImpl<ScanJobRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>storage.scan_job.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>storage.scan_job.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>storage.scan_job.file_id</code>.
     */
    public void setFileId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>storage.scan_job.file_id</code>.
     */
    public Long getFileId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>storage.scan_job.queue</code>.
     */
    public void setQueue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>storage.scan_job.queue</code>.
     */
    public String getQueue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>storage.scan_job.state</code>.
     */
    public void setState(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>storage.scan_job.state</code>.
     */
    public String getState() {
        return (String) get(3);
    }

    /**
     * Setter for <code>storage.scan_job.attempts</code>.
     */
    public void setAttempts(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>storage.scan_job.attempts</code>.
     */
    public Integer getAttempts() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>storage.scan_job.next_attempt_at</code>.
     */
    public void setNextAttemptAt(Instant value) {
        set(5, value);
    }

    /**
     * Getter for <code>storage.scan_job.next_attempt_at</code>.
     */
    public Instant getNextAttemptAt() {
        return (Instant) get(5);
    }

    /**
     * Setter for <code>storage.scan_job.lease_owner</code>.
     */
    public void setLeaseOwner(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>storage.scan_job.lease_owner</code>.
     */
    public String getLeaseOwner() {
        return (String) get(6);
    }

    /**
     * Setter for <code>storage.scan_job.lease_expires_at</code>.
     */
    public void setLeaseExpiresAt(Instant value) {
        set(7, value);
    }

    /**
     * Getter for <code>storage.scan_job.lease_expires_at</code>.
     */
    public Instant getLeaseExpiresAt() {
        return (Instant) get(7);
    }

    /**
     * Setter for <code>storage.scan_job.last_error</code>.
     */
    public void setLastError(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>storage.scan_job.last_error</code>.
     */
    public String getLastError() {
        return (String) get(8);
    }

    /**
     * Setter for <code>storage.scan_job.version</code>.
     */
    public void setVersion(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>storage.scan_job.version</code>.
     */
    public Long getVersion() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>storage.scan_job.created_at</code>.
     */
    public void setCreatedAt(Instant value) {
        set(10, value);
    }

    /**
     * Getter for <code>storage.scan_job.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(10);
    }

    /**
     * Setter for <code>storage.scan_job.updated_at</code>.
     */
    public void setUpdatedAt(Instant value) {
        set(11, value);
    }

    /**
     * Getter for <code>storage.scan_job.updated_at</code>.
     */
    public Instant getUpdatedAt() {
        return (Instant) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScanJobRecord
     */
    public ScanJobRecord() {
        super(ScanJob.SCAN_JOB);
    }

    /**
     * Create a detached, initialised ScanJobRecord
     */
    public ScanJobRecord(Long id, Long fileId, String queue, String state, Integer attempts, Instant nextAttemptAt, String leaseOwner, Instant leaseExpiresAt, String lastError, Long version, Instant createdAt, Instant updatedAt) {
        super(ScanJob.SCAN_JOB);

        setId(id);
        setFileId(fileId);
        setQueue(queue);
        setState(state);
        setAttempts(attempts);
        setNextAttemptAt(nextAttemptAt);
        setLeaseOwner(leaseOwner);
        setLeaseExpiresAt(leaseExpiresAt);
        setLastError(lastError);
        setVersion(version);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
