/*
 * This file is generated by jOOQ.
 */
package com.msj.securefile.infrastructure.persistence.jooq;


import com.msj.securefile.infrastructure.persistence.jooq.tables.File;
import com.msj.securefile.infrastructure.persistence.jooq.tables.ScanJob;
import com.msj.securefile.infrastructure.persistence.jooq.tables.ScanVerdict;
import com.msj.securefile.infrastructure.persistence.jooq.tables.records.FileRecord;
import com.msj.securefile.infrastructure.persistence.jooq.tables.records.ScanJobRecord;
import com.msj.securefile.infrastructure.persistence.jooq.tables.records.ScanVerdictRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FileRecord> FILE_PKEY = Internal.createUniqueKey(File.FILE, DSL.name("file_pkey"), new TableField[] { File.FILE.ID }, true);
    public static final UniqueKey<ScanJobRecord> SCAN_JOB_FILE_ID_KEY = Internal.createUniqueKey(ScanJob.SCAN_JOB, DSL.name("scan_job_file_id_key"), new TableField[] { ScanJob.SCAN_JOB.FILE_ID }, true);
    public static final UniqueKey<ScanJobRecord> SCAN_JOB_PKEY = Internal.createUniqueKey(ScanJob.SCAN_JOB, DSL.name("scan_job_pkey"), new TableField[] { ScanJob.SCAN_JOB.ID }, true);
    public static final UniqueKey<ScanVerdictRecord> SCAN_VERDICT_PKEY = Internal.createUniqueKey(ScanVerdict.SCAN_VERDICT, DSL.name("scan_verdict_pkey"), new TableField[] { ScanVerdict.SCAN_VERDICT.SHA256 }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ScanJobRecord, FileRecord> SCAN_JOB__SCAN_JOB_FILE_ID_FKEY = Internal.createForeignKey(ScanJob.SCAN_JOB, DSL.name("scan_job_file_id_fkey"), new TableField[] { ScanJob.SCAN_JOB.FILE_ID }, Keys.FILE_PKEY, new TableField[] { File.FILE.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
}
