/*
 * This file is generated by jOOQ.
 */
package com.msj.securefile.shared.infrastructure.persistence.jooq.storage;


import com.msj.securefile.shared.infrastructure.persistence.jooq.DefaultCatalog;
import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.tables.File;
import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.tables.ScanJob;
import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.tables.ScanVerdict;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Storage extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>storage</code>
     */
    public static final Storage STORAGE = new Storage();

    /**
     * The table <code>storage.file</code>.
     */
    public final File FILE = File.FILE;

    /**
     * The table <code>storage.scan_job</code>.
     */
    public final ScanJob SCAN_JOB = ScanJob.SCAN_JOB;

    /**
     * The table <code>storage.scan_verdict</code>.
     */
    public final ScanVerdict SCAN_VERDICT = ScanVerdict.SCAN_VERDICT;

    /**
     * No further instances allowed
     */
    private Storage() {
        super(DSL.name("storage"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            File.FILE,
            ScanJob.SCAN_JOB,
            ScanVerdict.SCAN_VERDICT
        );
    }
}
