/*
 * This file is generated by jOOQ.
 */
package com.msj.securefile.shared.infrastructure.persistence.jooq.storage;


import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.tables.File;
import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.tables.FileEvent;
import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.tables.ScanJob;
import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.tables.ScanVerdict;


/**
 * Convenience access to all tables in storage.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>storage.file</code>.
     */
    public static final File FILE = File.FILE;

    /**
     * The table <code>storage.file_event</code>.
     */
    public static final FileEvent FILE_EVENT = FileEvent.FILE_EVENT;

    /**
     * The table <code>storage.scan_job</code>.
     */
    public static final ScanJob SCAN_JOB = ScanJob.SCAN_JOB;

    /**
     * The table <code>storage.scan_verdict</code>.
     */
    public static final ScanVerdict SCAN_VERDICT = ScanVerdict.SCAN_VERDICT;
}
