/*
 * This file is generated by jOOQ.
 */
package com.msj.securefile.infrastructure.persistence.jooq.tables.records;


import com.msj.securefile.infrastructure.persistence.jooq.tables.ScanVerdict;

import java.time.Instant;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScanVerdictRecord extends UpdatableRecordImpl<ScanVerdictRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>scan_verdict.sha256</code>.
     */
    public void setSha256(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>scan_verdict.sha256</code>.
     */
    public String getSha256() {
        return (String) get(0);
    }

    /**
     * Setter for <code>scan_verdict.verdict</code>.
     */
    public void setVerdict(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>scan_verdict.verdict</code>.
     */
    public String getVerdict() {
        return (String) get(1);
    }

    /**
     * Setter for <code>scan_verdict.signature_name</code>.
     */
    public void setSignatureName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>scan_verdict.signature_name</code>.
     */
    public String getSignatureName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>scan_verdict.signature_version</code>.
     */
    public void setSignatureVersion(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>scan_verdict.signature_version</code>.
     */
    public String getSignatureVersion() {
        return (String) get(3);
    }

    /**
     * Setter for <code>scan_verdict.scanned_at</code>.
     */
    public void setScannedAt(Instant value) {
        set(4, value);
    }

    /**
     * Getter for <code>scan_verdict.scanned_at</code>.
     */
    public Instant getScannedAt() {
        return (Instant) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScanVerdictRecord
     */
    public ScanVerdictRecord() {
        super(ScanVerdict.SCAN_VERDICT);
    }

    /**
     * Create a detached, initialised ScanVerdictRecord
     */
    public ScanVerdictRecord(String sha256, String verdict, String signatureName, String signatureVersion, Instant scannedAt) {
        super(ScanVerdict.SCAN_VERDICT);

        setSha256(sha256);
        setVerdict(verdict);
        setSignatureName(signatureName);
        setSignatureVersion(signatureVersion);
        setScannedAt(scannedAt);
        resetTouchedOnNotNull();
    }
}
