/*
 * This file is generated by jOOQ.
 */
package com.msj.securefile.shared.infrastructure.persistence.jooq;


import com.msj.securefile.shared.infrastructure.persistence.jooq.tables.File;
import com.msj.securefile.shared.infrastructure.persistence.jooq.tables.ScanJob;
import com.msj.securefile.shared.infrastructure.persistence.jooq.tables.ScanVerdict;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * standard public schema
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>file</code>.
     */
    public final File FILE = File.FILE;

    /**
     * The table <code>scan_job</code>.
     */
    public final ScanJob SCAN_JOB = ScanJob.SCAN_JOB;

    /**
     * The table <code>scan_verdict</code>.
     */
    public final ScanVerdict SCAN_VERDICT = ScanVerdict.SCAN_VERDICT;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super(DSL.name(""), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            File.FILE,
            ScanJob.SCAN_JOB,
            ScanVerdict.SCAN_VERDICT
        );
    }
}
