/*
 * This file is generated by jOOQ.
 */
package com.msj.securefile.shared.infrastructure.persistence.jooq;


import com.msj.securefile.shared.infrastructure.persistence.jooq.tables.File;
import com.msj.securefile.shared.infrastructure.persistence.jooq.tables.ScanJob;
import com.msj.securefile.shared.infrastructure.persistence.jooq.tables.ScanVerdict;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>file</code>.
     */
    public static final File FILE = File.FILE;

    /**
     * The table <code>scan_job</code>.
     */
    public static final ScanJob SCAN_JOB = ScanJob.SCAN_JOB;

    /**
     * The table <code>scan_verdict</code>.
     */
    public static final ScanVerdict SCAN_VERDICT = ScanVerdict.SCAN_VERDICT;
}
