/*
 * This file is generated by jOOQ.
 */
package com.msj.securefile.shared.infrastructure.persistence.jooq.auth;


import com.msj.securefile.shared.infrastructure.persistence.jooq.DefaultCatalog;
import com.msj.securefile.shared.infrastructure.persistence.jooq.auth.tables.RefreshToken;
import com.msj.securefile.shared.infrastructure.persistence.jooq.auth.tables.Role;
import com.msj.securefile.shared.infrastructure.persistence.jooq.auth.tables.UserAccount;
import com.msj.securefile.shared.infrastructure.persistence.jooq.auth.tables.UserRole;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Auth extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>auth</code>
     */
    public static final Auth AUTH = new Auth();

    /**
     * The table <code>auth.refresh_token</code>.
     */
    public final RefreshToken REFRESH_TOKEN = RefreshToken.REFRESH_TOKEN;

    /**
     * The table <code>auth.role</code>.
     */
    public final Role ROLE = Role.ROLE;

    /**
     * The table <code>auth.user_account</code>.
     */
    public final UserAccount USER_ACCOUNT = UserAccount.USER_ACCOUNT;

    /**
     * The table <code>auth.user_role</code>.
     */
    public final UserRole USER_ROLE = UserRole.USER_ROLE;

    /**
     * No further instances allowed
     */
    private Auth() {
        super(DSL.name("auth"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            RefreshToken.REFRESH_TOKEN,
            Role.ROLE,
            UserAccount.USER_ACCOUNT,
            UserRole.USER_ROLE
        );
    }
}
