/*
 * This file is generated by jOOQ.
 */
package com.msj.securefile.shared.infrastructure.persistence.jooq.auth;


import com.msj.securefile.shared.infrastructure.persistence.jooq.auth.tables.RefreshToken;
import com.msj.securefile.shared.infrastructure.persistence.jooq.auth.tables.Role;
import com.msj.securefile.shared.infrastructure.persistence.jooq.auth.tables.UserAccount;
import com.msj.securefile.shared.infrastructure.persistence.jooq.auth.tables.UserRole;


/**
 * Convenience access to all tables in auth.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>auth.refresh_token</code>.
     */
    public static final RefreshToken REFRESH_TOKEN = RefreshToken.REFRESH_TOKEN;

    /**
     * The table <code>auth.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>auth.user_account</code>.
     */
    public static final UserAccount USER_ACCOUNT = UserAccount.USER_ACCOUNT;

    /**
     * The table <code>auth.user_role</code>.
     */
    public static final UserRole USER_ROLE = UserRole.USER_ROLE;
}
