/*
 * This file is generated by jOOQ.
 */
package com.msj.securefile.shared.infrastructure.persistence.jooq.auth.tables.records;


import com.msj.securefile.shared.infrastructure.persistence.jooq.auth.tables.RefreshToken;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RefreshTokenRecord extends UpdatableRecordImpl<RefreshTokenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>auth.refresh_token.token_hash</code>.
     */
    public void setTokenHash(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>auth.refresh_token.token_hash</code>.
     */
    public String getTokenHash() {
        return (String) get(0);
    }

    /**
     * Setter for <code>auth.refresh_token.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>auth.refresh_token.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>auth.refresh_token.expires_at</code>.
     */
    public void setExpiresAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>auth.refresh_token.expires_at</code>.
     */
    public LocalDateTime getExpiresAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>auth.refresh_token.revoked</code>.
     */
    public void setRevoked(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>auth.refresh_token.revoked</code>.
     */
    public Boolean getRevoked() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>auth.refresh_token.revoked_at</code>.
     */
    public void setRevokedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>auth.refresh_token.revoked_at</code>.
     */
    public LocalDateTime getRevokedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>auth.refresh_token.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>auth.refresh_token.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RefreshTokenRecord
     */
    public RefreshTokenRecord() {
        super(RefreshToken.REFRESH_TOKEN);
    }

    /**
     * Create a detached, initialised RefreshTokenRecord
     */
    public RefreshTokenRecord(String tokenHash, Long userId, LocalDateTime expiresAt, Boolean revoked, LocalDateTime revokedAt, LocalDateTime createdAt) {
        super(RefreshToken.REFRESH_TOKEN);

        setTokenHash(tokenHash);
        setUserId(userId);
        setExpiresAt(expiresAt);
        setRevoked(revoked);
        setRevokedAt(revokedAt);
        setCreatedAt(createdAt);
        resetTouchedOnNotNull();
    }
}
