/*
 * This file is generated by jOOQ.
 */
package com.msj.securefile.shared.infrastructure.persistence.jooq.auth.tables.records;


import com.msj.securefile.shared.infrastructure.persistence.jooq.auth.tables.UserAccount;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserAccountRecord extends UpdatableRecordImpl<UserAccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>auth.user_account.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>auth.user_account.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>auth.user_account.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>auth.user_account.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>auth.user_account.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>auth.user_account.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>auth.user_account.password</code>.
     */
    public void setPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>auth.user_account.password</code>.
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>auth.user_account.first_name</code>.
     */
    public void setFirstName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>auth.user_account.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>auth.user_account.last_name</code>.
     */
    public void setLastName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>auth.user_account.last_name</code>.
     */
    public String getLastName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>auth.user_account.enabled</code>.
     */
    public void setEnabled(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>auth.user_account.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>auth.user_account.account_non_expired</code>.
     */
    public void setAccountNonExpired(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>auth.user_account.account_non_expired</code>.
     */
    public Boolean getAccountNonExpired() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>auth.user_account.account_non_locked</code>.
     */
    public void setAccountNonLocked(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>auth.user_account.account_non_locked</code>.
     */
    public Boolean getAccountNonLocked() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>auth.user_account.credentials_non_expired</code>.
     */
    public void setCredentialsNonExpired(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>auth.user_account.credentials_non_expired</code>.
     */
    public Boolean getCredentialsNonExpired() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>auth.user_account.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>auth.user_account.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>auth.user_account.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>auth.user_account.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>auth.user_account.last_login_at</code>.
     */
    public void setLastLoginAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>auth.user_account.last_login_at</code>.
     */
    public LocalDateTime getLastLoginAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>auth.user_account.failed_login_attempts</code>.
     */
    public void setFailedLoginAttempts(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>auth.user_account.failed_login_attempts</code>.
     */
    public Integer getFailedLoginAttempts() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>auth.user_account.locked_until</code>.
     */
    public void setLockedUntil(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>auth.user_account.locked_until</code>.
     */
    public LocalDateTime getLockedUntil() {
        return (LocalDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserAccountRecord
     */
    public UserAccountRecord() {
        super(UserAccount.USER_ACCOUNT);
    }

    /**
     * Create a detached, initialised UserAccountRecord
     */
    public UserAccountRecord(Long id, String username, String email, String password, String firstName, String lastName, Boolean enabled, Boolean accountNonExpired, Boolean accountNonLocked, Boolean credentialsNonExpired, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime lastLoginAt, Integer failedLoginAttempts, LocalDateTime lockedUntil) {
        super(UserAccount.USER_ACCOUNT);

        setId(id);
        setUsername(username);
        setEmail(email);
        setPassword(password);
        setFirstName(firstName);
        setLastName(lastName);
        setEnabled(enabled);
        setAccountNonExpired(accountNonExpired);
        setAccountNonLocked(accountNonLocked);
        setCredentialsNonExpired(credentialsNonExpired);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setLastLoginAt(lastLoginAt);
        setFailedLoginAttempts(failedLoginAttempts);
        setLockedUntil(lockedUntil);
        resetTouchedOnNotNull();
    }
}
