/*
 * This file is generated by jOOQ.
 */
package com.msj.securefile.shared.infrastructure.persistence.jooq.auth.tables.records;


import com.msj.securefile.shared.infrastructure.persistence.jooq.auth.tables.UserRole;

import java.time.LocalDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserRoleRecord extends UpdatableRecordImpl<UserRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>auth.user_role.user_id</code>.
     */
    public void setUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>auth.user_role.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>auth.user_role.role_id</code>.
     */
    public void setRoleId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>auth.user_role.role_id</code>.
     */
    public Long getRoleId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>auth.user_role.assigned_at</code>.
     */
    public void setAssignedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>auth.user_role.assigned_at</code>.
     */
    public LocalDateTime getAssignedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>auth.user_role.assigned_by</code>.
     */
    public void setAssignedBy(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>auth.user_role.assigned_by</code>.
     */
    public Long getAssignedBy() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRoleRecord
     */
    public UserRoleRecord() {
        super(UserRole.USER_ROLE);
    }

    /**
     * Create a detached, initialised UserRoleRecord
     */
    public UserRoleRecord(Long userId, Long roleId, LocalDateTime assignedAt, Long assignedBy) {
        super(UserRole.USER_ROLE);

        setUserId(userId);
        setRoleId(roleId);
        setAssignedAt(assignedAt);
        setAssignedBy(assignedBy);
        resetTouchedOnNotNull();
    }
}
