/*
 * This file is generated by jOOQ.
 */
package com.msj.securefile.shared.infrastructure.persistence.jooq.tables.records;


import com.msj.securefile.shared.infrastructure.persistence.jooq.tables.File;

import java.time.Instant;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FileRecord extends UpdatableRecordImpl<FileRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>file.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>file.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>file.owner_id</code>.
     */
    public void setOwnerId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>file.owner_id</code>.
     */
    public Long getOwnerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>file.original_name</code>.
     */
    public void setOriginalName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>file.original_name</code>.
     */
    public String getOriginalName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>file.size_bytes</code>.
     */
    public void setSizeBytes(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>file.size_bytes</code>.
     */
    public Long getSizeBytes() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>file.sha256</code>.
     */
    public void setSha256(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>file.sha256</code>.
     */
    public String getSha256() {
        return (String) get(4);
    }

    /**
     * Setter for <code>file.status</code>.
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>file.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>file.created_at</code>.
     */
    public void setCreatedAt(Instant value) {
        set(6, value);
    }

    /**
     * Getter for <code>file.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(6);
    }

    /**
     * Setter for <code>file.updated_at</code>.
     */
    public void setUpdatedAt(Instant value) {
        set(7, value);
    }

    /**
     * Getter for <code>file.updated_at</code>.
     */
    public Instant getUpdatedAt() {
        return (Instant) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileRecord
     */
    public FileRecord() {
        super(File.FILE);
    }

    /**
     * Create a detached, initialised FileRecord
     */
    public FileRecord(Long id, Long ownerId, String originalName, Long sizeBytes, String sha256, String status, Instant createdAt, Instant updatedAt) {
        super(File.FILE);

        setId(id);
        setOwnerId(ownerId);
        setOriginalName(originalName);
        setSizeBytes(sizeBytes);
        setSha256(sha256);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
