/*
 * This file is generated by jOOQ.
 */
package com.msj.securefile.shared.infrastructure.persistence.jooq.auth.tables;


import com.msj.securefile.shared.infrastructure.persistence.jooq.auth.Auth;
import com.msj.securefile.shared.infrastructure.persistence.jooq.auth.Keys;
import com.msj.securefile.shared.infrastructure.persistence.jooq.auth.tables.RefreshToken.RefreshTokenPath;
import com.msj.securefile.shared.infrastructure.persistence.jooq.auth.tables.Role.RolePath;
import com.msj.securefile.shared.infrastructure.persistence.jooq.auth.tables.UserRole.UserRolePath;
import com.msj.securefile.shared.infrastructure.persistence.jooq.auth.tables.records.UserAccountRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserAccount extends TableImpl<UserAccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>auth.user_account</code>
     */
    public static final UserAccount USER_ACCOUNT = new UserAccount();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserAccountRecord> getRecordType() {
        return UserAccountRecord.class;
    }

    /**
     * The column <code>auth.user_account.id</code>.
     */
    public final TableField<UserAccountRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>auth.user_account.username</code>.
     */
    public final TableField<UserAccountRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>auth.user_account.email</code>.
     */
    public final TableField<UserAccountRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>auth.user_account.password</code>.
     */
    public final TableField<UserAccountRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>auth.user_account.first_name</code>.
     */
    public final TableField<UserAccountRecord, String> FIRST_NAME = createField(DSL.name("first_name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>auth.user_account.last_name</code>.
     */
    public final TableField<UserAccountRecord, String> LAST_NAME = createField(DSL.name("last_name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>auth.user_account.enabled</code>.
     */
    public final TableField<UserAccountRecord, Boolean> ENABLED = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>auth.user_account.account_non_expired</code>.
     */
    public final TableField<UserAccountRecord, Boolean> ACCOUNT_NON_EXPIRED = createField(DSL.name("account_non_expired"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>auth.user_account.account_non_locked</code>.
     */
    public final TableField<UserAccountRecord, Boolean> ACCOUNT_NON_LOCKED = createField(DSL.name("account_non_locked"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>auth.user_account.credentials_non_expired</code>.
     */
    public final TableField<UserAccountRecord, Boolean> CREDENTIALS_NON_EXPIRED = createField(DSL.name("credentials_non_expired"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>auth.user_account.created_at</code>.
     */
    public final TableField<UserAccountRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>auth.user_account.updated_at</code>.
     */
    public final TableField<UserAccountRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>auth.user_account.last_login_at</code>.
     */
    public final TableField<UserAccountRecord, LocalDateTime> LAST_LOGIN_AT = createField(DSL.name("last_login_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>auth.user_account.failed_login_attempts</code>.
     */
    public final TableField<UserAccountRecord, Integer> FAILED_LOGIN_ATTEMPTS = createField(DSL.name("failed_login_attempts"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>auth.user_account.locked_until</code>.
     */
    public final TableField<UserAccountRecord, LocalDateTime> LOCKED_UNTIL = createField(DSL.name("locked_until"), SQLDataType.LOCALDATETIME(6), this, "");

    private UserAccount(Name alias, Table<UserAccountRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserAccount(Name alias, Table<UserAccountRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>auth.user_account</code> table reference
     */
    public UserAccount(String alias) {
        this(DSL.name(alias), USER_ACCOUNT);
    }

    /**
     * Create an aliased <code>auth.user_account</code> table reference
     */
    public UserAccount(Name alias) {
        this(alias, USER_ACCOUNT);
    }

    /**
     * Create a <code>auth.user_account</code> table reference
     */
    public UserAccount() {
        this(DSL.name("user_account"), null);
    }

    public <O extends Record> UserAccount(Table<O> path, ForeignKey<O, UserAccountRecord> childPath, InverseForeignKey<O, UserAccountRecord> parentPath) {
        super(path, childPath, parentPath, USER_ACCOUNT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserAccountPath extends UserAccount implements Path<UserAccountRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserAccountPath(Table<O> path, ForeignKey<O, UserAccountRecord> childPath, InverseForeignKey<O, UserAccountRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserAccountPath(Name alias, Table<UserAccountRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserAccountPath as(String alias) {
            return new UserAccountPath(DSL.name(alias), this);
        }

        @Override
        public UserAccountPath as(Name alias) {
            return new UserAccountPath(alias, this);
        }

        @Override
        public UserAccountPath as(Table<?> alias) {
            return new UserAccountPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Auth.AUTH;
    }

    @Override
    public UniqueKey<UserAccountRecord> getPrimaryKey() {
        return Keys.USER_ACCOUNT_PKEY;
    }

    @Override
    public List<UniqueKey<UserAccountRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.USER_ACCOUNT_EMAIL_KEY, Keys.USER_ACCOUNT_USERNAME_KEY);
    }

    private transient RefreshTokenPath _refreshToken;

    /**
     * Get the implicit to-many join path to the <code>auth.refresh_token</code>
     * table
     */
    public RefreshTokenPath refreshToken() {
        if (_refreshToken == null)
            _refreshToken = new RefreshTokenPath(this, null, Keys.REFRESH_TOKEN__REFRESH_TOKEN_USER_ID_FKEY.getInverseKey());

        return _refreshToken;
    }

    private transient UserRolePath _userRole;

    /**
     * Get the implicit to-many join path to the <code>auth.user_role</code>
     * table
     */
    public UserRolePath userRole() {
        if (_userRole == null)
            _userRole = new UserRolePath(this, null, Keys.USER_ROLE__USER_ROLE_USER_ID_FKEY.getInverseKey());

        return _userRole;
    }

    /**
     * Get the implicit many-to-many join path to the <code>auth.role</code>
     * table
     */
    public RolePath role() {
        return userRole().role();
    }

    @Override
    public UserAccount as(String alias) {
        return new UserAccount(DSL.name(alias), this);
    }

    @Override
    public UserAccount as(Name alias) {
        return new UserAccount(alias, this);
    }

    @Override
    public UserAccount as(Table<?> alias) {
        return new UserAccount(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAccount rename(String name) {
        return new UserAccount(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAccount rename(Name name) {
        return new UserAccount(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAccount rename(Table<?> name) {
        return new UserAccount(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAccount where(Condition condition) {
        return new UserAccount(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAccount where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAccount where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAccount where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAccount where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAccount where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAccount where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAccount where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAccount whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAccount whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
