-- Initial schema. Timestamps have no DEFAULT on purpose: the application supplies them from its Clock.
-- Ids are TSIDs generated by the application (IdGenerator port), hence BIGINT without a sequence.
-- Each bounded context owns a schema and nothing lives in public.
-- owner_id is a plain column on purpose: the storage context does not depend on the auth schema.
-- The constraints repeat the invariants of the domain (SecureFile, ScanJob) as a last line of defence: the
-- database sees every writer, the Java code only sees itself.

CREATE SCHEMA storage;

-- One global status drives the lifecycle: UPLOADING -> PENDING -> SCANNING -> CLEAN | INFECTED | SCAN_FAILED,
-- plus UPLOAD_FAILED and SCANNING -> PENDING when a scan is handed back to the queue.
CREATE TABLE storage.file
(
    id                  BIGINT PRIMARY KEY,
    owner_id            BIGINT       NOT NULL,
    original_name       VARCHAR(255) NOT NULL,
    -- The declared size, checked equal to the measured one when the upload completes.
    size_bytes          BIGINT       NOT NULL CHECK (size_bytes >= 0),
    -- Unknown until the whole body has been read.
    sha256              CHAR(64) CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    status              VARCHAR(16)  NOT NULL CHECK (status IN
        ('UPLOADING', 'UPLOAD_FAILED', 'PENDING', 'SCANNING', 'CLEAN', 'INFECTED', 'SCAN_FAILED')),
    -- Past this instant a stuck upload may be failed by the reaper.
    upload_expires_at   TIMESTAMPTZ  NOT NULL,
    -- Why the upload failed. Set if and only if the status is UPLOAD_FAILED.
    failure_reason      VARCHAR(32) CHECK (failure_reason IN ('SIZE_MISMATCH', 'TIMEOUT', 'ABORTED', 'STORAGE_ERROR')),
    -- Signature reported by the scan. Set if and only if the status is INFECTED.
    infection_signature VARCHAR(255),
    -- Loaded version plus the events of the transaction: the compare-and-set guard of every update.
    version             BIGINT       NOT NULL CHECK (version >= 0),
    created_at          TIMESTAMPTZ  NOT NULL,
    updated_at          TIMESTAMPTZ  NOT NULL,
    CONSTRAINT file_sha256_by_status CHECK (
        (status IN ('UPLOADING', 'UPLOAD_FAILED') AND sha256 IS NULL)
            OR (status NOT IN ('UPLOADING', 'UPLOAD_FAILED') AND sha256 IS NOT NULL)),
    CONSTRAINT file_failure_reason_by_status CHECK ((status = 'UPLOAD_FAILED') = (failure_reason IS NOT NULL)),
    CONSTRAINT file_infection_signature_by_status CHECK ((status = 'INFECTED') = (infection_signature IS NOT NULL))
);

-- Every query is scoped to the owner (no IDOR): this serves "list my files".
CREATE INDEX idx_file_owner_created ON storage.file (owner_id, created_at DESC);
-- Reaper query: uploads past their deadline.
CREATE INDEX idx_file_upload_expiry ON storage.file (upload_expires_at) WHERE status = 'UPLOADING';

CREATE TABLE storage.scan_job
(
    id               BIGINT PRIMARY KEY,
    file_id          BIGINT      NOT NULL UNIQUE REFERENCES storage.file (id) ON DELETE CASCADE,
    -- Chosen from the file size, so a large scan never delays the small ones.
    queue            VARCHAR(8)  NOT NULL CHECK (queue IN ('SMALL', 'LARGE')),
    state            VARCHAR(16) NOT NULL CHECK (state IN ('PENDING', 'LEASED', 'DONE')),
    -- Counts failed scans only. A ClamAV outage releases the job without incrementing it.
    attempts         INTEGER     NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    next_attempt_at  TIMESTAMPTZ NOT NULL,
    -- A lease is held by exactly one worker: heartbeat, completion and failure are guarded on lease_owner.
    lease_owner      VARCHAR(128),
    lease_expires_at TIMESTAMPTZ,
    last_error       TEXT,
    version          BIGINT      NOT NULL CHECK (version >= 0),
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL,
    CONSTRAINT scan_job_lease_consistent CHECK (
        (state = 'LEASED' AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)
            OR (state <> 'LEASED' AND lease_owner IS NULL AND lease_expires_at IS NULL))
);

-- Claim query: WHERE queue = ? AND state = 'PENDING' AND next_attempt_at <= ? ... FOR UPDATE SKIP LOCKED.
CREATE INDEX idx_scan_job_claimable ON storage.scan_job (queue, next_attempt_at) WHERE state = 'PENDING';
-- Reaper query: leases that expired because a worker died.
CREATE INDEX idx_scan_job_lease_expiry ON storage.scan_job (lease_expires_at) WHERE state = 'LEASED';

-- Append-only audit trail of every state change of a file or of its scan job, written in the same transaction as the
-- state update. This is a log, not event sourcing: the tables above keep the current state.
-- No foreign key to storage.file on purpose: deleting a file must never delete its history.
CREATE TABLE storage.file_event
(
    id             BIGINT PRIMARY KEY,
    -- The file the event is about, also for the events of its scan job: one query gives the whole history.
    file_id        BIGINT      NOT NULL,
    aggregate_type VARCHAR(16) NOT NULL CHECK (aggregate_type IN ('FILE', 'SCAN_JOB')),
    aggregate_id   BIGINT      NOT NULL,
    -- Position of the event in its aggregate: loaded version plus its rank in the transaction, computed in memory.
    version        BIGINT      NOT NULL CHECK (version >= 1),
    event_type     VARCHAR(64) NOT NULL,
    payload        JSONB       NOT NULL,
    -- Who did it: the caller, a scan worker, or the system itself (reapers), which has no id.
    actor_type     VARCHAR(16) NOT NULL CHECK (actor_type IN ('USER', 'WORKER', 'SYSTEM')),
    actor_id       VARCHAR(128),
    occurred_at    TIMESTAMPTZ NOT NULL,
    -- Orders the events of an aggregate and rejects two writers that both think they hold the same version.
    CONSTRAINT file_event_aggregate_version_unique UNIQUE (aggregate_type, aggregate_id, version)
);

-- "History of this file", scan job included.
CREATE INDEX idx_file_event_file_occurred ON storage.file_event (file_id, occurred_at);

-- SHA-256 verdict cache. INFECTED is final. CLEAN is reusable only while signature_version
-- equals the one reported by clamd. A failed scan is never cached.
CREATE TABLE storage.scan_verdict
(
    sha256            CHAR(64) PRIMARY KEY CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    verdict           VARCHAR(16)  NOT NULL CHECK (verdict IN ('CLEAN', 'INFECTED')),
    signature_name    VARCHAR(255),
    signature_version VARCHAR(128) NOT NULL,
    scanned_at        TIMESTAMPTZ  NOT NULL,
    CONSTRAINT scan_verdict_signature_name_required CHECK (verdict = 'CLEAN' OR signature_name IS NOT NULL)
);