-- Initial schema. Timestamps have no DEFAULT on purpose: the application supplies them from its Clock.
-- Ids are TSIDs generated by the application (IdGenerator port), hence BIGINT without a sequence.
-- owner_id is a plain column: there is no user table until authentication is added.

CREATE TABLE file
(
    id            BIGINT PRIMARY KEY,
    owner_id      BIGINT       NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    size_bytes    BIGINT       NOT NULL CHECK (size_bytes >= 0),
    sha256        CHAR(64)     NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    status        VARCHAR(16)  NOT NULL CHECK (status IN ('PENDING', 'SCANNING', 'CLEAN', 'INFECTED', 'FAILED')),
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL
);

-- Every query is scoped to the owner (no IDOR): this serves "list my files".
CREATE INDEX idx_file_owner_created ON file (owner_id, created_at DESC);

CREATE TABLE scan_job
(
    id               BIGINT PRIMARY KEY,
    file_id          BIGINT      NOT NULL UNIQUE REFERENCES file (id) ON DELETE CASCADE,
    state            VARCHAR(16) NOT NULL CHECK (state IN ('PENDING', 'LEASED', 'DONE')),
    -- Counts failed scans only. A ClamAV outage requeues the job without incrementing it.
    attempts         INTEGER     NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    next_attempt_at  TIMESTAMPTZ NOT NULL,
    -- A lease is held by exactly one worker. attempts doubles as the fencing token on completion.
    lease_owner      VARCHAR(128),
    lease_expires_at TIMESTAMPTZ,
    last_error       TEXT,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL,
    CONSTRAINT scan_job_lease_consistent CHECK (
        (state = 'LEASED' AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)
            OR (state <> 'LEASED' AND lease_owner IS NULL AND lease_expires_at IS NULL))
);

-- Claim query: SELECT ... WHERE state = 'PENDING' AND next_attempt_at <= now() ... FOR UPDATE SKIP LOCKED.
CREATE INDEX idx_scan_job_claimable ON scan_job (next_attempt_at) WHERE state = 'PENDING';
-- Reaper query: leases that expired because a worker died.
CREATE INDEX idx_scan_job_lease_expiry ON scan_job (lease_expires_at) WHERE state = 'LEASED';

-- SHA-256 verdict cache. INFECTED is final. CLEAN is reusable only while signature_version
-- equals the one reported by clamd. FAILED is never cached.
CREATE TABLE scan_verdict
(
    sha256            CHAR(64) PRIMARY KEY CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    verdict           VARCHAR(16)  NOT NULL CHECK (verdict IN ('CLEAN', 'INFECTED')),
    signature_name    VARCHAR(255),
    signature_version VARCHAR(128) NOT NULL,
    scanned_at        TIMESTAMPTZ  NOT NULL,
    CONSTRAINT scan_verdict_signature_name_required CHECK (verdict = 'CLEAN' OR signature_name IS NOT NULL)
);