-- Authentication bounded context. Its own schema: nothing lives in public.
-- Ids are TSIDs generated by the application (IdGenerator port), hence BIGINT without a sequence.

CREATE SCHEMA auth;

CREATE TABLE auth.user_account
(
    id                      BIGINT PRIMARY KEY,
    username                VARCHAR(100) NOT NULL UNIQUE,
    email                   VARCHAR(255) NOT NULL UNIQUE,
    -- Holds the BCrypt hash, never the clear password.
    password                VARCHAR(255) NOT NULL,
    first_name              VARCHAR(100),
    last_name               VARCHAR(100),
    enabled                 BOOLEAN      NOT NULL DEFAULT TRUE,
    account_non_expired     BOOLEAN      NOT NULL DEFAULT TRUE,
    account_non_locked      BOOLEAN      NOT NULL DEFAULT TRUE,
    credentials_non_expired BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at           TIMESTAMP,
    failed_login_attempts   INTEGER      NOT NULL DEFAULT 0,
    locked_until            TIMESTAMP
);

CREATE TABLE auth.role
(
    id          BIGINT PRIMARY KEY,
    name        VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE auth.user_role
(
    user_id     BIGINT    NOT NULL REFERENCES auth.user_account (id) ON DELETE CASCADE,
    role_id     BIGINT    NOT NULL REFERENCES auth.role (id) ON DELETE CASCADE,
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_by BIGINT,
    PRIMARY KEY (user_id, role_id)
);

-- The primary key above already serves lookups by user_id. This one serves "who has this role".
CREATE INDEX idx_user_role_role_id ON auth.user_role (role_id);

-- The application refers to these ids (see JooqUserRepositoryAdapter): do not renumber.
INSERT INTO auth.role (id, name, description)
VALUES (1, 'ROLE_ADMIN', 'Administrator with full access'),
       (2, 'ROLE_USER', 'Regular user with basic access');

-- Server-side refresh token revocation (logout, logout everywhere, password change).
-- Only the hash is stored: a database leak does not leak usable tokens.
CREATE TABLE auth.refresh_token
(
    token_hash VARCHAR(64) PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES auth.user_account (id) ON DELETE CASCADE,
    expires_at TIMESTAMP   NOT NULL,
    revoked    BOOLEAN     NOT NULL DEFAULT FALSE,
    revoked_at TIMESTAMP,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_refresh_token_user_id ON auth.refresh_token (user_id);
-- Purge of expired tokens.
CREATE INDEX idx_refresh_token_expires_at ON auth.refresh_token (expires_at);
