/*
 * This file is generated by jOOQ.
 */
package com.msj.securefile.shared.infrastructure.persistence.jooq.storage.tables;


import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.Indexes;
import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.Keys;
import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.Storage;
import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.tables.records.FileEventRecord;

import java.time.Instant;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FileEvent extends TableImpl<FileEventRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>storage.file_event</code>
     */
    public static final FileEvent FILE_EVENT = new FileEvent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FileEventRecord> getRecordType() {
        return FileEventRecord.class;
    }

    /**
     * The column <code>storage.file_event.id</code>.
     */
    public final TableField<FileEventRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>storage.file_event.file_id</code>.
     */
    public final TableField<FileEventRecord, Long> FILE_ID = createField(DSL.name("file_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>storage.file_event.aggregate_type</code>.
     */
    public final TableField<FileEventRecord, String> AGGREGATE_TYPE = createField(DSL.name("aggregate_type"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>storage.file_event.aggregate_id</code>.
     */
    public final TableField<FileEventRecord, Long> AGGREGATE_ID = createField(DSL.name("aggregate_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>storage.file_event.version</code>.
     */
    public final TableField<FileEventRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>storage.file_event.event_type</code>.
     */
    public final TableField<FileEventRecord, String> EVENT_TYPE = createField(DSL.name("event_type"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>storage.file_event.payload</code>.
     */
    public final TableField<FileEventRecord, JSONB> PAYLOAD = createField(DSL.name("payload"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>storage.file_event.actor_type</code>.
     */
    public final TableField<FileEventRecord, String> ACTOR_TYPE = createField(DSL.name("actor_type"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>storage.file_event.actor_id</code>.
     */
    public final TableField<FileEventRecord, String> ACTOR_ID = createField(DSL.name("actor_id"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>storage.file_event.occurred_at</code>.
     */
    public final TableField<FileEventRecord, Instant> OCCURRED_AT = createField(DSL.name("occurred_at"), SQLDataType.INSTANT.nullable(false), this, "");

    private FileEvent(Name alias, Table<FileEventRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FileEvent(Name alias, Table<FileEventRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>storage.file_event</code> table reference
     */
    public FileEvent(String alias) {
        this(DSL.name(alias), FILE_EVENT);
    }

    /**
     * Create an aliased <code>storage.file_event</code> table reference
     */
    public FileEvent(Name alias) {
        this(alias, FILE_EVENT);
    }

    /**
     * Create a <code>storage.file_event</code> table reference
     */
    public FileEvent() {
        this(DSL.name("file_event"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Storage.STORAGE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_FILE_EVENT_FILE_OCCURRED);
    }

    @Override
    public UniqueKey<FileEventRecord> getPrimaryKey() {
        return Keys.FILE_EVENT_PKEY;
    }

    @Override
    public List<UniqueKey<FileEventRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.FILE_EVENT_AGGREGATE_VERSION_UNIQUE);
    }

    @Override
    public List<Check<FileEventRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("file_event_actor_type_check"), "(((actor_type)::text = ANY ((ARRAY['USER'::character varying, 'WORKER'::character varying, 'SYSTEM'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("file_event_aggregate_type_check"), "(((aggregate_type)::text = ANY ((ARRAY['FILE'::character varying, 'SCAN_JOB'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("file_event_version_check"), "((version >= 1))", true)
        );
    }

    @Override
    public FileEvent as(String alias) {
        return new FileEvent(DSL.name(alias), this);
    }

    @Override
    public FileEvent as(Name alias) {
        return new FileEvent(alias, this);
    }

    @Override
    public FileEvent as(Table<?> alias) {
        return new FileEvent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FileEvent rename(String name) {
        return new FileEvent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FileEvent rename(Name name) {
        return new FileEvent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FileEvent rename(Table<?> name) {
        return new FileEvent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileEvent where(Condition condition) {
        return new FileEvent(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileEvent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileEvent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileEvent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FileEvent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FileEvent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FileEvent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FileEvent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileEvent whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FileEvent whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
