/*
 * This file is generated by jOOQ.
 */
package com.msj.securefile.shared.infrastructure.persistence.jooq.storage.tables;


import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.Indexes;
import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.Keys;
import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.Storage;
import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.tables.ScanJob.ScanJobPath;
import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.tables.records.FileRecord;

import java.time.Instant;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class File extends TableImpl<FileRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>storage.file</code>
     */
    public static final File FILE = new File();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FileRecord> getRecordType() {
        return FileRecord.class;
    }

    /**
     * The column <code>storage.file.id</code>.
     */
    public final TableField<FileRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>storage.file.owner_id</code>.
     */
    public final TableField<FileRecord, Long> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>storage.file.original_name</code>.
     */
    public final TableField<FileRecord, String> ORIGINAL_NAME = createField(DSL.name("original_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>storage.file.size_bytes</code>.
     */
    public final TableField<FileRecord, Long> SIZE_BYTES = createField(DSL.name("size_bytes"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>storage.file.sha256</code>.
     */
    public final TableField<FileRecord, String> SHA256 = createField(DSL.name("sha256"), SQLDataType.CHAR(64).nullable(false), this, "");

    /**
     * The column <code>storage.file.status</code>.
     */
    public final TableField<FileRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>storage.file.created_at</code>.
     */
    public final TableField<FileRecord, Instant> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.INSTANT.nullable(false), this, "");

    /**
     * The column <code>storage.file.updated_at</code>.
     */
    public final TableField<FileRecord, Instant> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.INSTANT.nullable(false), this, "");

    private File(Name alias, Table<FileRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private File(Name alias, Table<FileRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>storage.file</code> table reference
     */
    public File(String alias) {
        this(DSL.name(alias), FILE);
    }

    /**
     * Create an aliased <code>storage.file</code> table reference
     */
    public File(Name alias) {
        this(alias, FILE);
    }

    /**
     * Create a <code>storage.file</code> table reference
     */
    public File() {
        this(DSL.name("file"), null);
    }

    public <O extends Record> File(Table<O> path, ForeignKey<O, FileRecord> childPath, InverseForeignKey<O, FileRecord> parentPath) {
        super(path, childPath, parentPath, FILE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class FilePath extends File implements Path<FileRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FilePath(Table<O> path, ForeignKey<O, FileRecord> childPath, InverseForeignKey<O, FileRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FilePath(Name alias, Table<FileRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FilePath as(String alias) {
            return new FilePath(DSL.name(alias), this);
        }

        @Override
        public FilePath as(Name alias) {
            return new FilePath(alias, this);
        }

        @Override
        public FilePath as(Table<?> alias) {
            return new FilePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Storage.STORAGE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_FILE_OWNER_CREATED);
    }

    @Override
    public UniqueKey<FileRecord> getPrimaryKey() {
        return Keys.FILE_PKEY;
    }

    private transient ScanJobPath _scanJob;

    /**
     * Get the implicit to-many join path to the <code>storage.scan_job</code>
     * table
     */
    public ScanJobPath scanJob() {
        if (_scanJob == null)
            _scanJob = new ScanJobPath(this, null, Keys.SCAN_JOB__SCAN_JOB_FILE_ID_FKEY.getInverseKey());

        return _scanJob;
    }

    @Override
    public List<Check<FileRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("file_sha256_check"), "((sha256 ~ '^[0-9a-f]{64}$'::text))", true),
            Internal.createCheck(this, DSL.name("file_size_bytes_check"), "((size_bytes >= 0))", true),
            Internal.createCheck(this, DSL.name("file_status_check"), "(((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SCANNING'::character varying, 'CLEAN'::character varying, 'INFECTED'::character varying, 'FAILED'::character varying])::text[])))", true)
        );
    }

    @Override
    public File as(String alias) {
        return new File(DSL.name(alias), this);
    }

    @Override
    public File as(Name alias) {
        return new File(alias, this);
    }

    @Override
    public File as(Table<?> alias) {
        return new File(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public File rename(String name) {
        return new File(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public File rename(Name name) {
        return new File(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public File rename(Table<?> name) {
        return new File(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public File where(Condition condition) {
        return new File(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public File where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public File where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public File where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public File where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public File where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public File where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public File where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public File whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public File whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
