/*
 * This file is generated by jOOQ.
 */
package com.msj.securefile.shared.infrastructure.persistence.jooq.storage.tables;


import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.Keys;
import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.Storage;
import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.tables.records.ScanVerdictRecord;

import java.time.Instant;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScanVerdict extends TableImpl<ScanVerdictRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>storage.scan_verdict</code>
     */
    public static final ScanVerdict SCAN_VERDICT = new ScanVerdict();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScanVerdictRecord> getRecordType() {
        return ScanVerdictRecord.class;
    }

    /**
     * The column <code>storage.scan_verdict.sha256</code>.
     */
    public final TableField<ScanVerdictRecord, String> SHA256 = createField(DSL.name("sha256"), SQLDataType.CHAR(64).nullable(false), this, "");

    /**
     * The column <code>storage.scan_verdict.verdict</code>.
     */
    public final TableField<ScanVerdictRecord, String> VERDICT = createField(DSL.name("verdict"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>storage.scan_verdict.signature_name</code>.
     */
    public final TableField<ScanVerdictRecord, String> SIGNATURE_NAME = createField(DSL.name("signature_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>storage.scan_verdict.signature_version</code>.
     */
    public final TableField<ScanVerdictRecord, String> SIGNATURE_VERSION = createField(DSL.name("signature_version"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>storage.scan_verdict.scanned_at</code>.
     */
    public final TableField<ScanVerdictRecord, Instant> SCANNED_AT = createField(DSL.name("scanned_at"), SQLDataType.INSTANT.nullable(false), this, "");

    private ScanVerdict(Name alias, Table<ScanVerdictRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ScanVerdict(Name alias, Table<ScanVerdictRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>storage.scan_verdict</code> table reference
     */
    public ScanVerdict(String alias) {
        this(DSL.name(alias), SCAN_VERDICT);
    }

    /**
     * Create an aliased <code>storage.scan_verdict</code> table reference
     */
    public ScanVerdict(Name alias) {
        this(alias, SCAN_VERDICT);
    }

    /**
     * Create a <code>storage.scan_verdict</code> table reference
     */
    public ScanVerdict() {
        this(DSL.name("scan_verdict"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Storage.STORAGE;
    }

    @Override
    public UniqueKey<ScanVerdictRecord> getPrimaryKey() {
        return Keys.SCAN_VERDICT_PKEY;
    }

    @Override
    public List<Check<ScanVerdictRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("scan_verdict_sha256_check"), "((sha256 ~ '^[0-9a-f]{64}$'::text))", true),
            Internal.createCheck(this, DSL.name("scan_verdict_signature_name_required"), "((((verdict)::text = 'CLEAN'::text) OR (signature_name IS NOT NULL)))", true),
            Internal.createCheck(this, DSL.name("scan_verdict_verdict_check"), "(((verdict)::text = ANY ((ARRAY['CLEAN'::character varying, 'INFECTED'::character varying])::text[])))", true)
        );
    }

    @Override
    public ScanVerdict as(String alias) {
        return new ScanVerdict(DSL.name(alias), this);
    }

    @Override
    public ScanVerdict as(Name alias) {
        return new ScanVerdict(alias, this);
    }

    @Override
    public ScanVerdict as(Table<?> alias) {
        return new ScanVerdict(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ScanVerdict rename(String name) {
        return new ScanVerdict(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ScanVerdict rename(Name name) {
        return new ScanVerdict(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ScanVerdict rename(Table<?> name) {
        return new ScanVerdict(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScanVerdict where(Condition condition) {
        return new ScanVerdict(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScanVerdict where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScanVerdict where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScanVerdict where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScanVerdict where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScanVerdict where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScanVerdict where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScanVerdict where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScanVerdict whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScanVerdict whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
