/*
 * This file is generated by jOOQ.
 */
package com.msj.securefile.shared.infrastructure.persistence.jooq.storage.tables;


import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.Indexes;
import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.Keys;
import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.Storage;
import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.tables.File.FilePath;
import com.msj.securefile.shared.infrastructure.persistence.jooq.storage.tables.records.ScanJobRecord;

import java.time.Instant;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScanJob extends TableImpl<ScanJobRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>storage.scan_job</code>
     */
    public static final ScanJob SCAN_JOB = new ScanJob();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScanJobRecord> getRecordType() {
        return ScanJobRecord.class;
    }

    /**
     * The column <code>storage.scan_job.id</code>.
     */
    public final TableField<ScanJobRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>storage.scan_job.file_id</code>.
     */
    public final TableField<ScanJobRecord, Long> FILE_ID = createField(DSL.name("file_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>storage.scan_job.queue</code>.
     */
    public final TableField<ScanJobRecord, String> QUEUE = createField(DSL.name("queue"), SQLDataType.VARCHAR(8).nullable(false), this, "");

    /**
     * The column <code>storage.scan_job.state</code>.
     */
    public final TableField<ScanJobRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>storage.scan_job.attempts</code>.
     */
    public final TableField<ScanJobRecord, Integer> ATTEMPTS = createField(DSL.name("attempts"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>storage.scan_job.next_attempt_at</code>.
     */
    public final TableField<ScanJobRecord, Instant> NEXT_ATTEMPT_AT = createField(DSL.name("next_attempt_at"), SQLDataType.INSTANT.nullable(false), this, "");

    /**
     * The column <code>storage.scan_job.lease_owner</code>.
     */
    public final TableField<ScanJobRecord, String> LEASE_OWNER = createField(DSL.name("lease_owner"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>storage.scan_job.lease_expires_at</code>.
     */
    public final TableField<ScanJobRecord, Instant> LEASE_EXPIRES_AT = createField(DSL.name("lease_expires_at"), SQLDataType.INSTANT, this, "");

    /**
     * The column <code>storage.scan_job.last_error</code>.
     */
    public final TableField<ScanJobRecord, String> LAST_ERROR = createField(DSL.name("last_error"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>storage.scan_job.version</code>.
     */
    public final TableField<ScanJobRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>storage.scan_job.created_at</code>.
     */
    public final TableField<ScanJobRecord, Instant> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.INSTANT.nullable(false), this, "");

    /**
     * The column <code>storage.scan_job.updated_at</code>.
     */
    public final TableField<ScanJobRecord, Instant> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.INSTANT.nullable(false), this, "");

    private ScanJob(Name alias, Table<ScanJobRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ScanJob(Name alias, Table<ScanJobRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>storage.scan_job</code> table reference
     */
    public ScanJob(String alias) {
        this(DSL.name(alias), SCAN_JOB);
    }

    /**
     * Create an aliased <code>storage.scan_job</code> table reference
     */
    public ScanJob(Name alias) {
        this(alias, SCAN_JOB);
    }

    /**
     * Create a <code>storage.scan_job</code> table reference
     */
    public ScanJob() {
        this(DSL.name("scan_job"), null);
    }

    public <O extends Record> ScanJob(Table<O> path, ForeignKey<O, ScanJobRecord> childPath, InverseForeignKey<O, ScanJobRecord> parentPath) {
        super(path, childPath, parentPath, SCAN_JOB);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ScanJobPath extends ScanJob implements Path<ScanJobRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ScanJobPath(Table<O> path, ForeignKey<O, ScanJobRecord> childPath, InverseForeignKey<O, ScanJobRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ScanJobPath(Name alias, Table<ScanJobRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ScanJobPath as(String alias) {
            return new ScanJobPath(DSL.name(alias), this);
        }

        @Override
        public ScanJobPath as(Name alias) {
            return new ScanJobPath(alias, this);
        }

        @Override
        public ScanJobPath as(Table<?> alias) {
            return new ScanJobPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Storage.STORAGE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_SCAN_JOB_CLAIMABLE, Indexes.IDX_SCAN_JOB_LEASE_EXPIRY);
    }

    @Override
    public UniqueKey<ScanJobRecord> getPrimaryKey() {
        return Keys.SCAN_JOB_PKEY;
    }

    @Override
    public List<UniqueKey<ScanJobRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.SCAN_JOB_FILE_ID_KEY);
    }

    @Override
    public List<ForeignKey<ScanJobRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SCAN_JOB__SCAN_JOB_FILE_ID_FKEY);
    }

    private transient FilePath _file;

    /**
     * Get the implicit join path to the <code>storage.file</code> table.
     */
    public FilePath file() {
        if (_file == null)
            _file = new FilePath(this, Keys.SCAN_JOB__SCAN_JOB_FILE_ID_FKEY, null);

        return _file;
    }

    @Override
    public List<Check<ScanJobRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("scan_job_attempts_check"), "((attempts >= 0))", true),
            Internal.createCheck(this, DSL.name("scan_job_lease_consistent"), "(((((state)::text = 'LEASED'::text) AND (lease_owner IS NOT NULL) AND (lease_expires_at IS NOT NULL)) OR (((state)::text <> 'LEASED'::text) AND (lease_owner IS NULL) AND (lease_expires_at IS NULL))))", true),
            Internal.createCheck(this, DSL.name("scan_job_queue_check"), "(((queue)::text = ANY ((ARRAY['SMALL'::character varying, 'LARGE'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("scan_job_state_check"), "(((state)::text = ANY ((ARRAY['PENDING'::character varying, 'LEASED'::character varying, 'DONE'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("scan_job_version_check"), "((version >= 0))", true)
        );
    }

    @Override
    public ScanJob as(String alias) {
        return new ScanJob(DSL.name(alias), this);
    }

    @Override
    public ScanJob as(Name alias) {
        return new ScanJob(alias, this);
    }

    @Override
    public ScanJob as(Table<?> alias) {
        return new ScanJob(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ScanJob rename(String name) {
        return new ScanJob(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ScanJob rename(Name name) {
        return new ScanJob(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ScanJob rename(Table<?> name) {
        return new ScanJob(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScanJob where(Condition condition) {
        return new ScanJob(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScanJob where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScanJob where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScanJob where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScanJob where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScanJob where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScanJob where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ScanJob where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScanJob whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ScanJob whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
